"""Compatibility facade for workspace scaffolding and state I/O."""

from __future__ import annotations

from research_os.project.legacy import (
    EAGER_DIRS,
    LAZY_DIRS,
    LAYOUT_SPEC,
    SCAFFOLD_PROFILES,
    TOP_LEVEL_DIRS,
    _read_project_name,
    _seed_mode_extras,
    _update_manifest,
    _prune_old_checkpoints,
    _insert_citation_entry,
    compute_file_hash,
    create_numbered_experiment,
    default_state,
    detect_software_components,
    describe_layout,
    ensure_lazy_dir,
    ensure_mode_surface,
    generate_citations_md,
    load_state,
    regenerate_intake,
    log_decision,
    manifest_path,
    mutate_state,
    now_iso,
    read_json,
    save_state,
    scaffold_minimal_workspace,
    slugify,
    state_json_path,
    state_path,
    write_json,
)
from research_os.project.layout import _compose_layout, _has_user_inputs, _resolve_scaffold_profile
from research_os.project.mcp_config import _setup_mcp_configs, mcp_global_install_hint, mcp_restart_notice, mcp_server_entry
from research_os.project.overrides import _OVERRIDE_RATIONALE_PLACEHOLDERS, enforce_override, log_override, validate_override_rationale
from research_os.project.sharing import _EXPORT_PY_TEMPLATE, _SHARE_EXCLUDE_NAMES, _get_export_py_template, _get_init_github_template, _get_sharing_doc_template, _write_sharing_scripts
from research_os.project.step_discovery import discover_step_dirs, is_path_container, resolve_step_dir, step_input_link, step_output_dir
from research_os.project.workflow import _atomic_write_text, _build_workflow_mermaid, _extract_path_lineage, _max_path_container_seq, _max_path_lineage, _update_analysis_mermaid_block, _update_workflow_mermaid

__all__ = [
    "EAGER_DIRS",
    "LAZY_DIRS",
    "LAYOUT_SPEC",
    "SCAFFOLD_PROFILES",
    "TOP_LEVEL_DIRS",
    "_read_project_name",
    "_seed_mode_extras",
    "_update_manifest",
    "_prune_old_checkpoints",
    "_insert_citation_entry",
    "compute_file_hash",
    "create_numbered_experiment",
    "default_state",
    "detect_software_components",
    "describe_layout",
    "ensure_lazy_dir",
    "ensure_mode_surface",
    "generate_citations_md",
    "load_state",
    "regenerate_intake",
    "log_decision",
    "manifest_path",
    "mutate_state",
    "now_iso",
    "read_json",
    "save_state",
    "scaffold_minimal_workspace",
    "slugify",
    "state_json_path",
    "state_path",
    "write_json",
    "LAYOUT_SPEC",
    "SCAFFOLD_PROFILES",
    "_compose_layout",
    "_has_user_inputs",
    "_resolve_scaffold_profile",
    "_setup_mcp_configs",
    "mcp_global_install_hint",
    "mcp_restart_notice",
    "mcp_server_entry",
    "_OVERRIDE_RATIONALE_PLACEHOLDERS",
    "enforce_override",
    "log_override",
    "validate_override_rationale",
    "_EXPORT_PY_TEMPLATE",
    "_SHARE_EXCLUDE_NAMES",
    "_get_export_py_template",
    "_get_init_github_template",
    "_get_sharing_doc_template",
    "_write_sharing_scripts",
    "discover_step_dirs",
    "is_path_container",
    "resolve_step_dir",
    "step_input_link",
    "step_output_dir",
    "_atomic_write_text",
    "_build_workflow_mermaid",
    "_extract_path_lineage",
    "_max_path_container_seq",
    "_max_path_lineage",
    "_update_analysis_mermaid_block",
    "_update_workflow_mermaid",
]
